[package]
name = "rust-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-clone-macro = { path = "./rust-clone-macro" }
criterion = "0.3.6"

[[bench]]
name = "clone_time"
harness = false